# Generated by Django 3.2 on 2022-05-24 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookJournalBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.bookjournalbase')),
                ('num_pages', models.BigIntegerField()),
                ('genre', models.CharField(max_length=255)),
            ],
            bases=('book.bookjournalbase',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.bookjournalbase')),
                ('type', models.CharField(choices=[('bullet', 'Bullet'), ('food', 'Food'), ('travel', 'Travel'), ('sport', 'Sport')], default='bullet', max_length=255)),
                ('publisher', models.CharField(max_length=255)),
            ],
            bases=('book.bookjournalbase',),
        ),
    ]
